version: '3.3'

services:

  db:
    image: postgres:13-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: mastan23/foodgram_b:v13
    restart: always
    volumes:
      - static_value:/backend/backend_static/
      - media_value:/backend/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: mastan23/foodgram_f:v2
    volumes:
      - ../frontend/:/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static_value:/var/html/backend_static/
      - ./media_value:/var/html/backend_media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - frontend

volumes:
  static_value:
  media_value: